services:
  app:
    build:
      context: .
      args:
        - VERSION=${VERSION:-latest}
    image: device-fleet:${VERSION:-latest}
    container_name: device-fleet-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/devicefleet?authSource=admin
    networks:
      - device-fleet-network

  mongodb:
    image: mongo:latest
    container_name: device-fleet-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=devicefleet
    volumes:
      - mongodb-data:/data/db
    networks:
      - device-fleet-network

networks:
  device-fleet-network:
    driver: bridge

volumes:
  mongodb-data: